#!/usr/bin/env bash
set -x

# shellcheck disable=SC2064
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

DIR="$1"
EXEC_FILE="$1/.fsaction"

if [ ! -d "$DIR" ]; then
	echo "'$DIR' is not a directory" >&2
	exit 1
fi


if [ ! -x "$EXEC_FILE" ]; then
	echo "'$EXEC_FILE' is not executable" >&2
	exit 1
fi

EXEC_FILE="$(realpath --canonicalize-existing --no-symlinks "${EXEC_FILE}")"

inotifywait -m -e close_write -e moved_to --no-newline --format '%w%f%0' "$DIR" \
	  | while IFS= read -r -d '' line; do

	set +e
	set +u
	event_on_file="$(realpath --canonicalize-existing --no-symlinks "${line}")"
	if [ -n "${event_on_file+set}" ]; then
		if [ -f "$event_on_file" ]; then
			( cd "$DIR" && "$EXEC_FILE" "$event_on_file" )
		fi
	fi
done
